export const ActionTypes = {
    SET_ALL_NOTES: "SET_ALL_NOTES",
    SET_SEARCHED_NOTES: "SET_SEARCHED_NOTES",
    SET_NOTE_TITLE:"SET_NOTE_TITLE",
    ADD_NOTE:"ADD_NOTE",
    VIEW_LIST:"VIEW_LIST",
    UPDATE_NOTE:"UPDATE_NOTE",
    DELETE_NOTE:"DELETE_NOTE"
  };